/**********************************************************************
 * Copyright by Jonas Thies, Univ. of Groningen 2006-2010.            *
 * Permission to use, copy, modify, redistribute is granted           *
 * as long as this header remains intact.                             *
 * contact: jonas@math.rug.nl                                         *
 **********************************************************************/
/**********************************************************************
 * Modified by T.E. Mulder, Utrecht University 2014/15                *
 * contact: t.e.mulder@uu.nl                                          *
 **********************************************************************/
#ifndef TRIOS_MACROS_H
#define TRIOS_MACROS_H

#include "GlobalDefinitions.H"
#include "THCMdefs.H"

#endif
